site_name: TinyLlama - ITX Llama
site_url: https://docs.retrodreams.ca/itxllama/
site_description: A collection of markdown encompassing documentation for each of the various TinyLlama projects.
repo_url: https://github.com/t3hbeowulf/tinyllama-docs
edit_uri: blob/main/docs/

nav:
  - Home: itxllama/index.md
  - Getting Started:
    - Unboxing: itxllama/getting-started.md
    - Jumpers: itxllama/getting-started-jumpers.md
    - First Boot: itxllama/getting-started-firstboot.md
    - Setup: itxllama/getting-started-setup.md
    - Setup DOS: itxllama/getting-started-setup-dos.md
    - Setup Windows 98: itxllama/getting-started-setup-win98.md
  - FAQ: itxllama/faq.md
  - Accessories: itxllama/accessories.md
  - MIDI: itxllama/midi.md
  - Compatibility Matrix: itxllama/compatibility-matrix.md
  # - TinyLlama: tinyllama/index.md
  # - TinyLlama2: tinyllama2/index.md
  # - ITX Llama: itxllama/index.md
  # - TinyLlama3: tinyllama3/index.md

theme: 
  name: mkdocs
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  user_color_mode_toggle: true
  color_mode: auto

markdown_extensions:
  - toc:
#      permalink: ÔÉÅ
      permalink: true
  - attr_list
  - def_list
  - tables
